server:
  port: 8790

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dantegarden/springcloudNetflix-demo-repo
          username: dantegarden
          password: your_password
          # git本地仓库地址
          basedir: /workspace/java/springcloudNetflix-demo/config-basedir/repo
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
